---
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ${root_module_folder_relative_path}/**

parameters:
  - name: terraform_action
    displayName: Terraform Action to perform
    type: string
    default: "apply"
    values:
      - "apply"
      - "destroy"
  - name: terraform_cli_version
    displayName: Terraform CLI Version
    type: string
    default: "latest"

lockBehavior: sequential

extends:
  template: ${cd_template_path}
  parameters:
    terraform_action: $${{ parameters.terraform_action }}
    root_module_folder_relative_path: ${root_module_folder_relative_path}
    terraform_cli_version: $${{ coalesce(parameters.terraform_cli_version, 'latest') }}
    backendAzureStorageAccountContainerKeyName: $(BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_KEY_NAME${sub_project_key_suffix})
